server.port=8080
spring.application.name=prod-eng-service
mongodb.connection.url=${MONGODB_CONECTION_URL:mongodb://root:example@localhost:27017}

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

management.metrics.tags.application=food-koala