{
 "title": "Restaurant Monitoring",
 "panels": [
  {
   "title": "Error Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Restaurant Lookup Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(app_restaurant_lookup_duration_seconds_sum[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Restaurants",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_active_restaurants", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Restaurant Create Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(app_restaurants_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}